'use strict';
const W=window.CrustWorld,R=W.RECIPES,KEY='crust-pizza-world-v2',$=id=>document.getElementById(id);
let s=W.fresh();try{const raw=JSON.parse(localStorage.getItem(KEY)||'null');if(raw?.version===2){W.normalize(raw);if(W.valid(raw))s=W.recover(raw);}else if(W.valid(raw))s=W.recover(raw);else s=W.migrate(JSON.parse(localStorage.getItem('crust-pizza-corner-v1')||'null'));}catch{}
W.normalize(s);
s.nightShift=s.nightShift===true;
let nightBlend=s.nightShift?1:0,nightLast=0;
const reducedMotion=window.matchMedia("(prefers-reduced-motion: reduce)");
function updateNightButton(){const b=$("nightShift");b.setAttribute("aria-pressed",String(s.nightShift));b.textContent=s.nightShift?"☀ DAY SHIFT":"☾ NIGHT SHIFT";document.body.classList.toggle("night-shift",s.nightShift);}
$("nightShift").onclick=()=>{s.nightShift=!s.nightShift;updateNightButton();save();};
updateNightButton();
if(!s.shopStarterBonus){s.coins+=500;s.shopStarterBonus=true;}
const canvas=$('game'),ctx=canvas.getContext('2d'),sprites={},customers=[];
const chef={x:2,z:2,path:[],task:null,sprite:'chef',facing:1};let chefAction=null,customerId=0,nextArrival=performance.now()+3500,lastFrame=0,paused=false,build=false,placement=null,hover=null,zoom=1,pan={x:0,y:0},view={},noticeTimeout,activeOven=null,floaters=[],hitboxes=[],pointer=null,panelMode='',lastHud=0;
const SPRITES=['oven','counter','cash','table','chair','plant','pizza','chef','female-front','female-back','male-front','male-back','oven-electric','oven-pro','chair-facing-table','sign-crust','sign-solana','city','plant-pink','table-pastel','sign-pizza','decor-lava','decor-hover','sign-neon','table-holo','table-orbit','counter-cyber','fryer','soda','bus_station','garbage_can','sink','dishwasher'];
const names=['Mia','Leo','Ruby','Alex','Jamie','Noor'];
function save(){try{const savedAt=Date.now(),waitingOrders=[...customers.filter(c=>['counter','ordered'].includes(c.phase)&&!s.pending.some(p=>p.id===c.id)).map(c=>({recipe:c.recipe,name:c.name})),...(s.waitingOrders||[])].slice(0,4);localStorage.setItem(KEY,JSON.stringify({...s,savedAt,waitingOrders}));s.savedAt=savedAt;const cloud=window.CrustApi?.isAuthed?.();$('saveStatus').textContent=(cloud?'☁ Cloud + ':'')+'✓ Auto-save · '+new Date(savedAt).toLocaleTimeString('en-US',{hour:'2-digit',minute:'2-digit'});if(window.CrustApi?.queueSync)window.CrustApi.queueSync(s);return true;}catch{$('saveStatus').textContent='Save failed · Browser storage unavailable';return false;}}
function notify(message){$('notice').textContent=message;$('notice').classList.add('show');clearTimeout(noticeTimeout);noticeTimeout=setTimeout(()=>$('notice').classList.remove('show'),3500);}
function openPanel(html,mode=''){$('panelBody').innerHTML=html;panelMode=mode;if(!$('panel').open)$('panel').showModal();}
function closePanel(){$('panel').close();panelMode='';}
function hud(){updateOrderBadge();const l=W.level(s);$('coins').textContent=Math.floor(s.coins).toLocaleString('en-US');$('level').textContent=l;$('xpLabel').textContent=`${s.xp%30} / 30 XP`;$('xpFill').style.width=(s.xp%30/30*100)+'%';$('served').textContent=`${s.served} happy customer${s.served===1?'':'s'}`;const ra=s.ratingCount?s.ratingAvg:5;$('rating').textContent='★ '+ra.toFixed(1);const expansion=W.expansionInfo(s);$('expansionBadge').textContent=expansion.purchased+'/'+expansion.total;const tips=s.objects.reduce((a,o)=>a+(o.tip||0),0);$('tipsBadge').hidden=!tips;$('tipsBadge').textContent=tips;let step=1,title='Your guests choose the menu',hint='Open Orders to see what they want.';if(s.objects.some(o=>o.job)){step=2;title='Let your chef work';hint='Tap the oven when its pizza is ready.';}if(W.stock(s).some(n=>n>0)||customers.some(c=>c.phase!=='exit')){step=3;title='Your first customers are here';hint='Prepare their order, then tap Serve.';}if(tips){step=4;title='A little thank-you on the table';hint='Tap the coin to collect your tip.';}else if(s.served){step=4;title='Your corner is coming to life';hint='Cook more, or rearrange your furniture.';}if(build){step='↔';title='Make this corner yours';hint='Tap a piece, then tap an empty floor tile.';}$('objective').innerHTML=`<span class="objective-icon">${step}</span><div><b>${title}</b><small>${hint}</small></div>`;}
function find(id){return s.objects.find(o=>o.id===id);}
function allOvens(){return s.objects.filter(o=>o.type==='oven');}
function chooseOven(){const ovens=allOvens();if(ovens.length===1){ovenPanel(ovens[0]);return;}openPanel(`<div class="panel-kicker">YOUR KITCHEN</div><h2>Choose an oven</h2><p class="panel-intro">Each oven cooks one batch at a time.</p>${ovens.map((o,i)=>`<div class="shop-card"><img src="assets/${W.spriteName(o)}.png" alt=""><div class="card-description"><strong>${W.oven(o).name} ${i+1}</strong><small>${o.job?(o.job.end<=Date.now()?'Ready to collect':R[o.job.recipe].name+' is baking'):o.dirty?'Needs cleaning':'Ready to cook'}</small></div><button class="action-btn" data-oven="${o.id}">Open</button></div>`).join('')}`,'ovens');}
function ovenPanel(o){if(!o)return;activeOven=o.id;const busy=chefAction!==null,model=W.oven(o);if(o.job){const ready=o.job.end<=Date.now();openPanel(`<div class="panel-kicker">${model.name.toUpperCase()}</div><h2>${R[o.job.recipe].name}</h2><p class="panel-intro">${ready?'Your batch is ready. Send the chef to put it on the display counter.':'The oven is doing its thing. You can close this window and watch your restaurant.'}</p><div class="mini-stats"><div><b id="bakeClock">${ready?'Ready!':Math.ceil((o.job.end-Date.now())/1000)+'s'}</b><small>BAKING TIME</small></div><div><b>4</b><small>SERVINGS</small></div></div><button class="action-btn" id="collectBatch" ${!ready||busy?'disabled':''}>${busy?'Chef is busy':'Collect pizza'}</button>`,'oven');return;}
if(W.canCleanStation(o)){openPanel(`<div class="panel-kicker">A FRESH START</div><h2>Deep clean</h2><p class="panel-intro">This station has been used ${o.usesSinceClean} times. Cleaning is optional but lowers grime and helps your rating.${o.grime?' Grime level: '+o.grime+'.':''}</p><button class="action-btn green" id="cleanOven" ${busy?'disabled':''}>${busy?'Chef is busy':'Clean station · +1 XP'}</button>`,'oven');return;}
openPanel(`<div class="panel-kicker">RECIPE BOOK</div><h2>What’s cooking?</h2><p class="panel-intro">${model.name}: four pizzas per batch. ${model.time===1?'Standard baking time.':Math.round((1-model.time)*100)+'% shorter baking time.'} Your chef walks over to start.</p>${R.map((r,i)=>{if(r.side)return '';const locked=W.level(s)<r.level;return `<div class="recipe-card"><img src="assets/pizza.png" alt="${r.name}"><div class="card-description"><strong>${r.name}</strong><small>${locked?'Unlocks at level '+r.level:r.description+'<br>'+W.bakeTime(o,r)/1000+'s · sell for '+r.price+' coins each'}</small></div><button class="action-btn" data-recipe="${i}" ${locked||busy||s.coins<r.cost?'disabled':''}>${locked?'Locked':busy?'Busy':'Bake · '+r.cost}</button></div>`;}).join('')}`,'recipes');}
function sideStation(recipe){const st=R[recipe]?.station;return st?s.objects.find(o=>o.type===st):null;}
function sendChef(o,action,recipe){if(chefAction){notify('Your chef is already on the way.');return;}const reserved=customers.filter(c=>['counter','cash','seat','wait_order','ordered'].includes(c.phase)).map(c=>c.target||{x:Math.round(c.x),z:Math.round(c.z)});const target=W.approach(s,chef,o,reserved);if(!target){notify('The chef cannot reach this station. Leave a walkway.');return;}chefAction={id:o.id,action,recipe};chef.path=target.path;chef.target=target.end;chef.task='work';closePanel();notify(action==='side'?'Your chef is heading to the '+R[recipe].name.replace(/ .*/,'')+' station.':action==='bake'?'Your chef is heading to the oven.':action==='collect'?'Chef is collecting the pizza.':'Time to clean the station.');}
function finishChef(){const a=chefAction;if(!a)return;const old=W.level(s);let ok=false;if(a.action==='side')ok=W.prepareSide(s,a.recipe,Date.now(),a.id);if(a.action==='bake')ok=W.bake(s,a.id,a.recipe,Date.now());if(a.action==='collect')ok=W.collect(s,a.id,Date.now());if(a.action==='clean')ok=W.clean(s,a.id);chefAction=null;chef.task=null;chef.target=null;if(ok){save();hud();notify(a.action==='side'?'Preparing sides now.':a.action==='bake'?'Pizza is baking. Watch the timer above the oven.':a.action==='collect'?'Four servings are on the counter. Open for business!':'Station cleaned. Rating will thank you.');if(W.level(s)>old)levelUp();}else notify('That action is not available now.');}
function levelUp(){notify(`Level ${W.level(s)}! ${W.level(s)===2?'Pepperoni unlocked.':W.level(s)===3?'Garden Party unlocked.':'Your pizzeria is growing.'}`);}
function settleCustomers(){s.waitingOrders=[...customers.filter(c=>['counter','ordered'].includes(c.phase)&&!s.pending.some(p=>p.id===c.id)).map(c=>({recipe:c.recipe,name:c.name})),...(s.waitingOrders||[])].slice(0,4);for(const c of customers){const pending=s.pending.find(p=>p.id===c.id);if(pending){if(pending.paid){s.served++;s.xp+=5;const t=find(pending.table);if(t)t.tip=(t.tip||0)+2;}else{const counter=find(c.counter)||s.objects.find(o=>o.type==='counter');counter.stock[pending.recipe]++;}}}s.pending=[];customers.length=0;save();}
function beginBuild(){if(chefAction){notify('Wait until your chef finishes this action.');return false;}settleCustomers();build=true;placement=null;chef.x=W.entry(s).x;chef.z=W.entry(s).z;chef.path=[];$('buildBar').hidden=false;$('decorate').classList.add('active');$('buildMessage').textContent='Tap a piece to move it, or buy something new.';$('rotate').hidden=true;$('cancelPlace').hidden=true;hud();return true;}
function shop(){openShop();}
function typeLabel(o){if(o.type==='oven')return W.oven(o).name;if(W.isSign(o))return o.design==='neon'?'In Crust We Trust neon':o.design==='crust'?'crust&co sign':o.design==='pizza'?'Happy pizza plaque':'Solana sign';const k=shopKey?.(o);return W.TYPES[k]?.name||o.type;}
function startPlacement(key,id=null){const o=id?find(id):W.makeObject(key,s.nextId);if(!o)return;if(!id&&W.level(s)<(W.TYPES[key]?.level||1)){notify('Reach level '+W.TYPES[key].level+' to unlock this.');return;}hideShop();placement={object:{...o},original:id,price:id?0:W.TYPES[key]?.price||0};const label=typeLabel(o);$('buildMessage').textContent=`${id?'Move':'Place'} ${label}. ${W.isSign(o)?'Tap either back wall.':'Tap an empty floor tile.'}`;$('rotate').hidden=!['chair','decor'].includes(o.type);$('cancelPlace').hidden=false;$('storeItem').hidden=!id;closePanel();if(!id)notify('Choose a spot to place it. Cancel keeps purchased items in Storage.');}
function cancelPlacement(){placement=null;$('storeItem').hidden=true;$('buildMessage').textContent='Tap a piece to move it, or buy something new.';$('rotate').hidden=true;$('cancelPlace').hidden=true;}
function parkChef(){const spots=[{x:2,z:2},{x:1,z:1},{x:3,z:2},{x:2,z:3}];const free=spots.find(p=>W.inside(s,p)&&!W.at(s,p.x,p.z)&&!customers.some(c=>Math.hypot(c.x-p.x,c.z-p.z)<.8));if(free){chef.x=free.x;chef.z=free.z;}else{const e=W.entry(s);const p=W.path(s,e,{x:2,z:2});if(p?.length){chef.x=p[0].x;chef.z=p[0].z;}}chef.path=[];chef.target=null;}
function finishBuild(){hideShop();if(placement)cancelPlacement();build=false;$('buildBar').hidden=true;$('decorate').classList.remove('active');parkChef();nextArrival=performance.now()+1500;hud();save();}
function placeAt(tile){if(!tile)return;const obj={...placement.object,x:tile.x,z:tile.z};const v=W.placement(s,obj);if(!v.ok){notify(v.reason);return;}if(s.coins<placement.price+12&&placement.price){notify('Keep 12 coins for your next batch.');return;}if(placement.original)Object.assign(find(placement.original),obj);else{if(placement.stored){s.inventory=s.inventory.filter(o=>o.id!==obj.id);}if(obj.type==='oven'&&!placement.stored){obj.job=null;obj.usesSinceClean=0;obj.grime=0;}if(obj.type==='table'||obj.type==='chair')obj.tip=0;if(obj.type==='counter')obj.stock=R.map(()=>0);if(obj.type==='bus_station'){obj.trash=0;obj.dishes=0;}s.objects.push(obj);if(!placement.stored)s.nextId++;s.coins-=placement.price;}cancelPlacement();chef.x=W.entry(s).x;chef.z=W.entry(s).z;save();hud();notify('Placed and saved! Tap SHOP to buy another item, or press Done.');}
function expansion(){const e=W.expansionInfo(s),price=e.price,missing=e.max?0:Math.max(0,price+12-s.coins);openPanel(`<div class="panel-kicker">EXPANSION ${e.purchased} OF ${e.total}</div><h2>${e.max?'Your biggest corner yet':'Make room for more'}</h2><p class="panel-intro">${e.max?'All 20 expansions are complete. Enjoy your 28 × 28 restaurant.':`Grow your ${s.size} × ${s.size} restaurant to ${e.nextSize} × ${e.nextSize}. Your furniture stays in place.`}</p><div class="expansion-progress" aria-label="${e.purchased} of 20 expansions complete">${W.EXPANSION_PRICES.map((_,i)=>`<span class="${i<e.purchased?'complete':i===e.purchased?'next':''}"></span>`).join('')}</div>${!e.max?`<div class="mini-stats"><div><b>${price.toLocaleString('en-US')}</b><small>COINS · EXPANSION ${e.purchased+1}</small></div><div><b>${e.nextSize} × ${e.nextSize}</b><small>NEXT ROOM SIZE</small></div></div><button class="action-btn green" id="buyExpansion" ${missing||chefAction?'disabled':''}>Expand now · ${price.toLocaleString('en-US')} coins</button><p class="expansion-note">${chefAction?'Wait for your chef to finish.':missing?'Save '+missing.toLocaleString('en-US')+' more coins, including 12 for ingredients.':'12 coins stay available for your next recipe.'}</p>`:''}<details class="expansion-roadmap"><summary>View all 20 expansions</summary><table><thead><tr><th>Step</th><th>Room</th><th>Coins</th></tr></thead><tbody>${W.EXPANSION_PRICES.map((cost,i)=>`<tr class="${i<e.purchased?'owned':i===e.purchased?'up-next':''}"><td>${i<e.purchased?'✓ ':''}${i+1}${i===e.purchased?' · Next':''}</td><td>${W.START_SIZE+i+1} × ${W.START_SIZE+i+1}</td><td>${cost.toLocaleString('en-US')}</td></tr>`).join('')}</tbody></table></details>`,'expand');}
function takeTip(o){if(!o.tip){notify('Happy customers leave tips after eating.');return;}const n=o.tip;s.coins+=n;o.tip=0;money(o.x,o.z,n);save();hud();}
function collectAllTips(){let n=0;for(const o of s.objects){n+=o.tip||0;if(o.type==='table'||o.type==='chair')o.tip=0;}if(!n){notify('Tips will appear on chairs after customers eat.');return;}s.coins+=n;save();hud();notify(`Collected ${n} coins in tips. Thank you!`);}
function help(){openPanel(`<div class="panel-kicker">WELCOME, CHEF</div><h2>Your own pizza corner</h2><ol class="help-list"><li>Guests choose from your unlocked menu. Open <b>Orders</b> and prepare exactly what they ask for.</li><li>Fries and cola need a <b>frying station</b> and <b>soda dispenser</b> (SHOP → OVENS) before guests can order them.</li><li>Hire a <b>Waiter</b> so 40% of guests dine in: they order at the table instead of the counter line.</li><li>After meals, mess goes to the <b>bussing station</b>. Janitors and Dishwashers need the bus station, garbage can, and sink or dishwasher.</li><li>Kitchen stations can be cleaned after <b>3 uses</b> (optional). Skipping cleans builds grime and lowers your ★ rating.</li><li>Buy <b>tables</b> and <b>chairs</b> separately in Furniture. Tap tip coins on chairs to seat the next guest.</li></ol><p class="help-note">Drag empty space to look around. Use + / − to zoom. Progress saves in this browser.</p><button class="action-btn" id="gotIt">Let’s cook</button>`,'help');}
function counterPanel(o){openPanel(`<div class="panel-kicker">FRESH FROM THE OVEN</div><h2>On the counter</h2><p class="panel-intro">Prepared food and drinks stay here until you serve the matching customer order.</p>${R.map((r,i)=>`<div class="recipe-card">${r.side?`<span class="food-icon" role="img" aria-label="${r.name}">${r.icon}</span>`:`<img src="assets/pizza.png" alt="${r.name}">`}<div class="card-description"><strong>${r.name}</strong><small>${r.price} coins per serving</small></div><strong>${o.stock[i]} left</strong></div>`).join('')}`,'stock');}
function routeTo(c,o,phase){
 const reserved=customers.filter(other=>other!==c&&other.phase!=='exit').map(other=>other.target||other);
 if(chef.target)reserved.push(chef.target);reserved.push(chef);
 const candidates=[];
 for(let radius=1;radius<=3;radius++)for(let x=Math.max(0,o.x-radius);x<=Math.min(s.size-1,o.x+radius);x++)for(let z=Math.max(0,o.z-radius);z<=Math.min(s.size-1,o.z+radius);z++){
  const end={x,z};if(Math.abs(x-o.x)+Math.abs(z-o.z)!==radius||W.at(s,x,z)||reserved.some(q=>Math.hypot(q.x-x,q.z-z)<.9))continue;
  const exits=[[1,0],[-1,0],[0,1],[0,-1]].filter(([dx,dz])=>W.inside(s,{x:x+dx,z:z+dz})&&!W.at(s,x+dx,z+dz));if(exits.length<2)continue;
  const path=W.path(s,c,end);if(path)candidates.push({end,path,rank:radius*100+path.length});
 }
 const a=candidates.sort((a,b)=>a.rank-b.rank)[0];if(!a)return false;c.path=a.path;c.target=a.end;c.phase=phase;c.wait=0;return true;
}
function guestMenu(){return R.map((r,i)=>({r,i})).filter(({i})=>W.recipeAvailable(s,i)&&(s.coins>=R[i].cost||W.stock(s)[i]>0||s.objects.some(o=>o.job?.recipe===i)||s.sideJob?.recipe===i));}
function spawnGuest(now){if(build||customers.length>=4)return;const entrance=W.entry(s);if(customers.some(c=>Math.hypot(c.x-entrance.x,c.z-entrance.z)<.85)||Math.hypot(chef.x-entrance.x,chef.z-entrance.z)<.85)return;const reserved=new Set(customers.filter(c=>c.phase!=='exit').map(c=>c.table));const chairs=s.objects.filter(o=>o.type==='chair'&&!o.tip&&!reserved.has(o.id)&&!(o.messTrash||o.messDishes));const counters=s.objects.filter(o=>o.type==='counter');if(!chairs.length||!counters.length)return;const counter=counters[0],saved=s.waitingOrders?.[0],menu=guestMenu(),recipe=saved?saved.recipe:(menu.length?menu[Math.floor(Math.random()*menu.length)].i:0),index=customerId%names.length,e=W.entry(s);const dineIn=s.staff.includes('waiter')&&Math.random()<W.SEATED_MIX;const seat=chairs[Math.floor(Math.random()*chairs.length)];const c={id:++customerId,x:e.x,z:e.z,path:[],phase:dineIn?'seat':'counter',dineIn,table:seat.id,counter:counter.id,recipe,name:saved?.name||names[index],gender:customerId%2?'female':'male',facing:1,wait:0,orderWait:0,orderPlaced:false};if(dineIn){if(!routeTo(c,seat,'seat'))return;notify(c.name+' is taking a table.');}else{if(!routeTo(c,counter,'counter'))return;notify(c.name+' ordered '+R[recipe].name+'.');}if(saved)s.waitingOrders.shift();customers.push(c);updateOrderBadge();}
function move(a,dt){if(!a.path.length)return false;const t=a.path[0],dx=t.x-a.x,dz=t.z-a.z,d=Math.hypot(dx,dz),speed=dt*2.2;if(dx+dz<0)a.facing=-1;else if(dx+dz>0)a.facing=1;if(d<=speed){a.x=t.x;a.z=t.z;a.path.shift();}else{a.x+=dx/d*speed;a.z+=dz/d*speed;}return true;}
function exitGuest(c){c.yielding=null;c.phase='exit';c.path=W.path(s,c,W.entry(s),true)||[];c.target=W.entry(s);c.wait=0;c.exitTime=0;}
function people(){return [chef,...customers];}
function trafficPath(a,end){
 const blocked=new Set(s.objects.flatMap(W.cells).map(p=>p.x+','+p.z));
 for(const other of people())if(other!==a)blocked.add(Math.round(other.x)+','+Math.round(other.z));
 if(people().some(o=>o!==a&&Math.hypot(o.x-end.x,o.z-end.z)<.68))return null;
 return W.path(s,a,end,a.phase==='table',blocked);
}
function stepAside(a,requester){
 if(a.yielding||a.phase==='eat')return false;
 const origin={x:Math.round(a.x),z:Math.round(a.z)},options=[];
 for(const [dx,dz] of [[1,0],[0,1],[-1,0],[0,-1]]){
  const p={x:origin.x+dx,z:origin.z+dz};
  if(!W.inside(s,p)||W.at(s,p.x,p.z)||people().some(o=>o!==a&&(Math.hypot(o.x-p.x,o.z-p.z)<.85||o.target&&o!==requester&&Math.hypot(o.target.x-p.x,o.target.z-p.z)<.5)))continue;
  if(requester.path.slice(0,3).some(q=>q.x===p.x&&q.z===p.z))continue;
  const route=trafficPath(a,p);if(route?.length)options.push({p,route});
 }
 const choice=options.sort((a,b)=>a.route.length-b.route.length)[0];if(!choice)return false;
 a.yielding={resume:a.target?{...a.target}:null,hold:0};a.path=choice.route;a.blocked=0;return true;
}
function moveInTraffic(a,dt){
 if(a.yielding&&!a.path.length){
  a.yielding.hold+=dt;if(a.yielding.hold<.65)return true;
  const end=a.yielding.resume;
  if(!end){a.yielding=null;return false;}
  const route=trafficPath(a,end);if(!route)return true;
  a.path=route;a.yielding=null;
 }
 if(!a.path.length)return false;
 const t=a.path[0],dx=t.x-a.x,dz=t.z-a.z,d=Math.hypot(dx,dz);
 if(d<.001){a.path.shift();return true;}
 const step=Math.min(dt*2.2,d),nx=a.x+dx/d*step,nz=a.z+dz/d*step;
 const blocker=people().find(o=>o!==a&&Math.hypot(nx-o.x,nz-o.z)<.68);
 if(blocker){
  a.blocked=(a.blocked||0)+dt;
  if(a.blocked>.55){
   const end=a.yielding?a.path.at(-1):a.target,route=end&&trafficPath(a,end);
   if(route?.length)a.path=route;
   else if(!blocker.yielding&&!stepAside(blocker,a))stepAside(a,blocker);
   a.blocked=0;
  }
  return true;
 }
 a.blocked=0;return move(a,dt);
}
function moveChef(dt){return moveInTraffic(chef,dt);}
function moveGuest(c,dt){return moveInTraffic(c,dt);}
function finishMeal(c){const seat=find(c.table);if(seat){seat.tip=(seat.tip||0)+Math.max(1,Math.round(2*W.cleanlinessFactor(s)));seat.messTrash=1;seat.messDishes=1;}const rs=W.reviewScore(c,s);W.recordReview(s,rs);W.trackRecipeReview(s,c.recipe,rs);W.addFloorDirt(s);s.pending=s.pending.filter(p=>p.id!==c.id);const old=W.level(s);s.served++;s.xp+=5;if(W.level(s)>old)levelUp();floaters.push({guest:c,kind:'reaction',life:2,text:['🍕 One more slice!','🔥 Worth every coin!','💜 In crust we trust!'][Math.floor(Math.random()*3)]});exitGuest(c);save();hud();}
function customerStep(c,dt){
 if(['counter','ordered'].includes(c.phase)&&!c.serveRequested){c.orderWait=(c.orderWait||0)+dt;if(c.orderWait>=60){notify(c.name+' waited too long and left upset.');W.recordReview(s,1);exitGuest(c);updateOrderBadge();return;}}
 if(c.phase==='exit'){c.exitTime=(c.exitTime||0)+dt;if(c.exitTime>14){customers.splice(customers.indexOf(c),1);return;}}
 if(moveGuest(c,dt))return;c.wait+=dt;
if(c.phase==='seat'&&!c.path.length&&c.wait>.5){c.phase='wait_order';c.wait=0;}
else if(c.phase==='wait_order'&&s.staff.includes('waiter')&&c.wait>1.2&&!c.orderPlaced){c.orderPlaced=true;c.phase='ordered';c.orderWait=0;notify(c.name+' ordered '+R[c.recipe].name+' at the table.');updateOrderBadge();}
else if(c.phase==='counter'&&c.wait>.8&&c.serveRequested){const counter=find(c.counter);if(!counter||counter.stock[c.recipe]<=0){c.serveRequested=false;return;}counter.stock[c.recipe]--;s.pending.push({id:c.id,recipe:c.recipe,table:c.table,paid:false});c.carry=true;c.wait=0;const cash=s.objects.find(o=>o.type==='cash');if(!routeTo(c,cash,'cash')){counter.stock[c.recipe]++;s.pending=s.pending.filter(p=>p.id!==c.id);c.carry=false;exitGuest(c);}save();}
else if(c.phase==='cash'&&c.wait>1.1){const p=s.pending.find(p=>p.id===c.id);if(p&&!p.paid){const mult=W.cleanlinessFactor(s);p.paid=true;s.coins+=Math.max(1,Math.round(R[c.recipe].price*mult));money(c.x,c.z,Math.round(R[c.recipe].price*mult));floaters.push({x:c.x,z:c.z,guest:c,kind:'payment',life:2.8,text:'✓ Transaction confirmed · SlicePay'});}const seat=find(c.table);const dest={x:seat.x,z:seat.z};c.path=W.path(s,c,dest,true)||[];c.target=dest;c.phase='table';c.wait=0;save();hud();}
else if(c.phase==='ordered'&&c.wait>.8&&c.serveRequested){const counter=find(c.counter);if(!counter||counter.stock[c.recipe]<=0){c.serveRequested=false;return;}counter.stock[c.recipe]--;c.carry=true;c.wait=0;c.phase='eat';c.facing=-1;c.serveRequested=false;const mult=W.cleanlinessFactor(s);s.coins+=Math.max(1,Math.round(R[c.recipe].price*mult));money(c.x,c.z,Math.round(R[c.recipe].price*mult));save();}
else if(c.phase==='table'){c.phase='eat';c.wait=0;c.carry=false;c.facing=-1;}
else if(c.phase==='eat'&&c.wait>5.5)finishMeal(c);
else if(c.phase==='exit'&&c.wait>.4){customers.splice(customers.indexOf(c),1);}
}
let staffTimer=0;
function busStation(){return s.objects.find(o=>o.type==='bus_station');}
function workStaff(dt){
 staffTimer+=dt;if(staffTimer<2)return;staffTimer=0;
 if(s.staff.includes('cleaner')){const st=s.objects.find(o=>['oven','fryer','soda'].includes(o.type)&&W.canCleanStation(o)&&!o.job&&chefAction?.id!==o.id);if(st){const old=W.level(s);W.clean(s,st.id);save();hud();if(W.level(s)>old)levelUp();}}
 if(s.staff.includes('server')){const guest=customers.find(c=>c.phase==='counter'&&!c.serveRequested&&!c.path.length&&c.wait>.8&&find(c.counter)?.stock?.[c.recipe]>0);if(guest){guest.serveRequested=true;notify('Counter server served '+guest.name+'’s order.');}}
 if(s.staff.includes('server')){const seated=customers.find(c=>c.phase==='ordered'&&!c.serveRequested&&!c.path.length&&c.wait>.8&&W.stock(s)[c.recipe]>0);if(seated){seated.serveRequested=true;notify('Counter server brought '+R[seated.recipe].name+' to '+seated.name+'.');}}
 if(s.staff.includes('prep')&&!s.sideJob&&chefAction?.action!=='side'){const guest=customers.find(c=>['counter','ordered'].includes(c.phase)&&!c.serveRequested&&R[c.recipe].side&&W.stock(s)[c.recipe]===0&&s.coins>=R[c.recipe].cost+12);if(guest){const st=sideStation(guest.recipe);if(st&&W.prepareSide(s,guest.recipe,Date.now(),st.id)){save();hud();notify('Sides helper is preparing '+R[guest.recipe].name+'.');}}}
 if(s.staff.includes('waiter')){const bus=busStation();const mess=s.objects.find(o=>o.type==='chair'&&(o.messTrash||o.messDishes));if(bus&&mess){if(mess.messTrash){bus.trash=Math.min(W.BUS_CAP,(bus.trash||0)+1);mess.messTrash=0;}if(mess.messDishes){bus.dishes=Math.min(W.BUS_CAP,(bus.dishes||0)+1);mess.messDishes=0;}save();}}
 if(s.staff.includes('janitor')){const bus=busStation(),can=s.objects.find(o=>o.type==='garbage_can');if(bus?.trash>0&&can){bus.trash--;s.floorDirt=Math.max(0,(s.floorDirt||0)-8);save();hud();}else if((s.floorDirt||0)>5){s.floorDirt=Math.max(0,s.floorDirt-4);save();}}
 if(s.staff.includes('dishwasher')&&!s.washJob){const bus=busStation();if(bus?.dishes>0){const washer=s.objects.find(o=>o.type==='dishwasher')||s.objects.find(o=>o.type==='sink');if(washer){bus.dishes--;s.washJob={end:Date.now()+W.washTime(s,washer),dishes:1};save();}}}
}
function money(x,z,n){floaters.push({x,z,text:'+'+n,life:1.8});}
function resize(){const dpr=Math.min(window.devicePixelRatio||1,2);canvas.width=Math.round(innerWidth*dpr);canvas.height=Math.round(innerHeight*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);layout();}
function layout(){const w=innerWidth,h=innerHeight,tx=Math.min(48,(w-50)/(2*s.size),Math.max(120,h-215)/(s.size+1.8))*zoom,ty=tx*.5;view={w,h,tx,ty,x:w*.5+pan.x,y:h*.53-(s.size-1)*ty+pan.y,wall:tx*1.8};}
function zoomLimit(){return Math.max(2.8,s.size/5);}
function changeZoom(amount){zoom=Math.max(.65,Math.min(zoomLimit(),zoom+amount));}
function fitRoom(){zoom=1;pan={x:0,y:0};}
function drawCity(){const img=sprites.city;if(!img)return;const baseScale=Math.max(view.w/img.width,view.h/img.height,(2*s.size*view.tx/zoom)/(1217*.9)),scale=baseScale*zoom,w=img.width*scale,h=img.height*scale;const center=project((s.size-1)/2,(s.size-1)/2);ctx.drawImage(img,center.x-768*scale,center.y-552*scale,w,h);}
function project(x,z){return{x:view.x+(x-z)*view.tx,y:view.y+(x+z)*view.ty};}
function tileAt(x,y){const a=(x-view.x)/view.tx,b=(y-view.y)/view.ty;return{x:Math.round((a+b)/2),z:Math.round((b-a)/2)};}
function pointInPolygon(x,y,pts){let inside=false;for(let i=0,j=pts.length-1;i<pts.length;j=i++){const a=pts[i],b=pts[j];if(((a.y>y)!==(b.y>y))&&(x<(b.x-a.x)*(y-a.y)/(b.y-a.y)+a.x))inside=!inside;}return inside;}
function wallTileAt(x,y){for(let i=0;i<s.size;i++){for(const side of ['left','right']){const a=side==='left'?project(-.5,i-.5):project(i-.5,-.5),b=side==='left'?project(-.5,i+.5):project(i+.5,-.5);const pts=[a,b,{x:b.x,y:b.y-view.wall},{x:a.x,y:a.y-view.wall}];if(pointInPolygon(x,y,pts))return side==='left'?{x:0,z:i}:{x:i,z:0};}}return null;}
function placementTileAt(x,y){return placement&&W.isSign(placement.object)?(wallTileAt(x,y)||tileAt(x,y)):tileAt(x,y);}
function wallSign(o,alpha=1,register=true){const img=sprites[W.spriteName(o)];if(!img)return;const left=o.x===0,p=left?project(-.5,o.z):project(o.x,-.5),w=view.tx*(o.design==='pizza'?1:1.6),h=w*img.height/img.width,cy=p.y-view.wall*.53,k=left?-.5:.5;ctx.save();ctx.globalAlpha=alpha;if(o.design==='neon'){ctx.shadowColor='#68f3d7';ctx.shadowBlur=4+nightBlend*7+(reducedMotion.matches?0:3*Math.sin(performance.now()/950));}ctx.translate(p.x,cy);ctx.transform(1,k,0,1,0,0);ctx.drawImage(img,-w/2,-h/2,w,h);ctx.restore();if(register)hitboxes.push({id:o.id,x:p.x-w/2,y:cy-h/2-w*.25,w,h:h+w*.5});}
function polygon(points,fill,stroke,width=1){ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=width;ctx.stroke();}}
function tile(x,z,color,line){const p=project(x,z);polygon([{x:p.x,y:p.y-view.ty},{x:p.x+view.tx,y:p.y},{x:p.x,y:p.y+view.ty},{x:p.x-view.tx,y:p.y}],color,line);}
function sciFiWall(a,b,paper){
 const h=view.wall,n=Math.max(4,s.size),w=96;
 ctx.save();ctx.transform((b.x-a.x)/(n*w),(b.y-a.y)/(n*w),0,1,a.x,a.y-h);
 ctx.beginPath();ctx.rect(0,0,n*w,h);ctx.clip();ctx.lineWidth=1.8;
 for(let i=0;i<n;i++){
  const x=i*w;ctx.strokeStyle=paper.trim+'88';ctx.strokeRect(x+6,12,w-12,h-24);
  if(paper.pattern==='circuit'){
   ctx.strokeStyle='#70ffe1';ctx.beginPath();ctx.moveTo(x+18,h*.77);ctx.lineTo(x+18,h*.47);ctx.lineTo(x+42,h*.47);ctx.lineTo(x+42,h*.23);ctx.lineTo(x+73,h*.23);ctx.stroke();
   ctx.strokeStyle='#53bddd';ctx.beginPath();ctx.moveTo(x+74,h*.78);ctx.lineTo(x+74,h*.59);ctx.lineTo(x+53,h*.59);ctx.stroke();
   for(const [dx,dy] of [[18,.77],[73,.23],[53,.59]]){ctx.fillStyle='#adfff0';ctx.beginPath();ctx.arc(x+dx,h*dy,3,0,Math.PI*2);ctx.fill();}
  }else{
   ctx.fillStyle='#7958aa';ctx.beginPath();for(let j=0;j<6;j++){const ang=Math.PI/3*j;const px=x+48+25*Math.cos(ang),py=h*.48+25*Math.sin(ang);j?ctx.lineTo(px,py):ctx.moveTo(px,py);}ctx.closePath();ctx.fill();ctx.strokeStyle='#e1a7ff';ctx.stroke();
   ctx.fillStyle='#9cf9ff';ctx.fillRect(x+23,h*.78,50,3);ctx.fillStyle='#ffe4ff';ctx.beginPath();ctx.arc(x+48,h*.48,4,0,Math.PI*2);ctx.fill();
  }
 }
 ctx.restore();
}
function wall(a,b,color){const h=view.wall;polygon([a,b,{x:b.x,y:b.y-h},{x:a.x,y:a.y-h}],color,'#c99570',1);if(s.wallpaper&&s.wallpaper!=='classic'){const paper=W.WALLPAPERS[s.wallpaper];if(paper.pattern){sciFiWall(a,b,paper);}else for(let i=0;i<16;i+=2){const t=i/16,u=(i+1)/16;polygon([{x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t},{x:a.x+(b.x-a.x)*u,y:a.y+(b.y-a.y)*u},{x:a.x+(b.x-a.x)*u,y:a.y+(b.y-a.y)*u-h},{x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t-h}],paper.colors[1]+'99');}}polygon([{x:a.x,y:a.y-h},{x:b.x,y:b.y-h},{x:b.x,y:b.y-h+view.tx*.25},{x:a.x,y:a.y-h+view.tx*.25}],(W.WALLPAPERS[s.wallpaper]||W.WALLPAPERS.classic).trim);for(let t=0;t<1;t+=.075){const u=Math.min(1,t+.035);polygon([{x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t-h},{x:a.x+(b.x-a.x)*u,y:a.y+(b.y-a.y)*u-h},{x:a.x+(b.x-a.x)*u,y:a.y+(b.y-a.y)*u-h+view.tx*.25},{x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t-h+view.tx*.25}],'#ffeac0');}}
function sprite(name,x,z,width,options={}){const img=sprites[name];if(!img)return;const crop=name==='decor-lava'?[.30,0,.40,1]:name==='decor-hover'?[.23,0,.54,1]:[0,0,1,1],sx=img.width*crop[0],sy=img.height*crop[1],sw=img.width*crop[2],sh=img.height*crop[3];const p=project(x,z),w=view.tx*width,h=w*sh/sw,base=p.y+view.ty*.55-(options.raise||0)*view.tx,bob=options.bob||0;ctx.save();ctx.globalAlpha=options.alpha??1;if(options.glow){ctx.shadowColor=options.glow;ctx.shadowBlur=options.glowSize||5;}if(options.flip){ctx.translate(p.x,base+bob);ctx.scale(-1,1);ctx.drawImage(img,sx,sy,sw,sh,-w/2,-h,w,h);}else ctx.drawImage(img,sx,sy,sw,sh,p.x-w/2,base-h+bob,w,h);ctx.restore();if(options.id)hitboxes.push({id:options.id,x:p.x-w/2,y:base-h,w,h});}
function rounded(x,y,w,h,r,fill,stroke){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=1.5;ctx.stroke();}}
function label(x,z,text,color='#fff9df',offset=1.8){const p=project(x,z),font=Math.max(10,view.tx*.29);ctx.font=`bold ${font}px Trebuchet MS,Arial`;const width=ctx.measureText(text).width+16,y=p.y-offset*view.tx;rounded(p.x-width/2,y-14,width,24,8,color,'#b58a59');ctx.textAlign='center';ctx.fillStyle='#62442d';ctx.fillText(text,p.x,y+2);}
function nightCity(now){
 const dt=nightLast?Math.min((now-nightLast)/1000,.1):0;nightLast=now;
 const target=s.nightShift?1:0;nightBlend=reducedMotion.matches?target:nightBlend+(target-nightBlend)*Math.min(1,dt*3);
 if(nightBlend<.002)return;
 ctx.save();ctx.globalAlpha=nightBlend;
 const tint=ctx.createLinearGradient(0,0,view.w,view.h);tint.addColorStop(0,'rgba(30,20,79,.78)');tint.addColorStop(.6,'rgba(17,43,88,.65)');tint.addColorStop(1,'rgba(42,21,76,.73)');ctx.fillStyle=tint;ctx.fillRect(0,0,view.w,view.h);
 // Rain is painted before the opaque restaurant floor and walls, keeping it outdoors.
 if(!reducedMotion.matches){ctx.strokeStyle='rgba(181,220,255,.35)';ctx.lineWidth=1;ctx.beginPath();for(let i=0;i<65;i++){const x=((i*137.53-now*.035)%(view.w+80)+view.w+80)%(view.w+80)-40,y=(i*89.17+now*(.17+(i%4)*.025))%(view.h+60)-30;ctx.moveTo(x,y);ctx.lineTo(x-4,y+12);}ctx.stroke();}
 ctx.restore();
}
function draw(now){layout();const v=view;ctx.clearRect(0,0,v.w,v.h);ctx.fillStyle='#badd92';ctx.fillRect(0,0,v.w,v.h);drawCity();nightCity(now);
// Floor diamonds are the interactive placement grid; all furnishings are separate sprite assets.
const n=s.size,top=project(-.5,-.5),left=project(-.5,n-.5),right=project(n-.5,-.5),bottom=project(n-.5,n-.5);
polygon([{x:left.x,y:left.y+3},{x:bottom.x,y:bottom.y+3},{x:right.x,y:right.y+3},{x:right.x,y:right.y+12},{x:bottom.x,y:bottom.y+12},{x:left.x,y:left.y+12}],'#be8964');
const floor=W.FLOORS[s.floor]||W.FLOORS.classic;
const dirtA=Math.min(.35,(s.floorDirt||0)/100*.35);for(let z=0;z<n;z++)for(let x=0;x<n;x++){tile(x,z,W.floorColor(s.floor,x,z),build?'#ae926388':floor.line);if(dirtA>.02){const p=project(x,z);polygon([{x:p.x,y:p.y-view.ty},{x:p.x+view.tx,y:p.y},{x:p.x,y:p.y+view.ty},{x:p.x-view.tx,y:p.y}],`rgba(80,60,40,${dirtA})`);}if(floor.pattern==='planks'){const a=project(x-.5,z),b=project(x+.5,z);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.strokeStyle=floor.line;ctx.lineWidth=1;ctx.stroke();}}
const paper=W.WALLPAPERS[s.wallpaper]||W.WALLPAPERS.classic;wall(left,top,paper.colors[0]);wall(top,right,paper.colors[1]);
hitboxes=[];for(const o of s.objects)if(W.isSign(o)&&placement?.original!==o.id)wallSign(o);
const e=W.entry(s);tile(e.x,e.z,'#e9cb97','#bb9561');const ep=project(e.x,e.z);ctx.save();ctx.font=`bold ${Math.max(10,v.tx*.3)}px Trebuchet MS`;ctx.textAlign='center';ctx.fillStyle='#ab8353';ctx.fillText('WELCOME',ep.x,ep.y+3);ctx.restore();
if(build&&hover&&W.inside(s,hover)){let good=true;if(placement)good=W.placement(s,{...placement.object,...hover}).ok;tile(hover.x,hover.z,good?'#95d680aa':'#ea715ca0',good?'#4f9c49':'#b74639');}
const layers=[];for(const o of s.objects){if(placement?.original===o.id||W.isSign(o))continue;if(o.type==='chair')layers.push({depth:o.x+o.z+.25,fn:()=>{sprite(W.spriteName(o),o.x,o.z,.95,{flip:o.rot===1,id:o.id});if(o.messTrash||o.messDishes)label(o.x,o.z,'🗑️'+(o.messDishes?'🍽':''),'#ffe8c8',1.1);const eating=customers.find(c=>c.table===o.id&&c.phase==='eat');if(eating){if(R[eating.recipe].side)label(o.x,o.z,R[eating.recipe].icon,'#fff9df',.8);else sprite('pizza',o.x,o.z,.55,{raise:.58});}}});else if(o.type==='table')layers.push({depth:o.x+o.z+.3,fn:()=>sprite(W.spriteName(o),o.x,o.z,1.65,{id:o.id})});else layers.push({depth:o.x+o.z+.3,fn:()=>{sprite(W.spriteName(o),o.x,o.z,o.type==='plant'?1.05:o.variant==='lava'?.85:1.65,{id:o.id,flip:o.type==='decor'&&o.rot===1,bob:o.variant==='hover'&&!reducedMotion.matches?Math.sin(now/850)*view.tx*.06:0,glow:o.variant==='lava'?'#ff79c6':null,glowSize:5+nightBlend*7+(reducedMotion.matches?0:3*Math.sin(now/1100))});if(o.type==='counter'&&o.stock.some(q=>q>0)){const recipe=o.stock.findIndex(q=>q>0);if(R[recipe].side)label(o.x,o.z,R[recipe].icon,'#fff9df',1.1);else sprite('pizza',o.x,o.z,.62,{raise:.95});}}});}
layers.push({depth:chef.x+chef.z+.1,fn:()=>sprite('chef',chef.x,chef.z,.77,{flip:chef.facing<0,bob:chef.path.length?Math.sin(now/100)*1.3:0})});
for(const c of customers)layers.push({depth:c.x+c.z+.12,fn:()=>{sprite(c.gender+(c.facing<0?'-back':'-front'),c.x,c.z,.74,{flip:c.phase==='eat'&&find(c.table)?.rot===1,bob:c.path.length?Math.sin(now/100)*1.4:0,raise:c.phase==='eat'?.45:0});if(c.carry){if(R[c.recipe].side)label(c.x,c.z,R[c.recipe].icon,'#fff9df',1);else sprite('pizza',c.x+.15,c.z,.43,{raise:.5});}if(c.phase==='wait_order')label(c.x,c.z,'Menu?','#fff9df',2);}});
layers.sort((a,b)=>a.depth-b.depth).forEach(l=>l.fn());
for(const o of s.objects){if(o.type==='oven'){let text=o.job?(o.job.end<=Date.now()?'READY ✓':Math.ceil((o.job.end-Date.now())/1000)+'s'):W.canCleanStation(o)?'Clean':'Cook +';label(o.x,o.z,text,o.job&&o.job.end<=Date.now()?'#e0f5bb':'#fff9df',2.35);}if(o.type==='fryer'||o.type==='soda'){let text=s.sideJob&&s.sideJob.stationId===o.id?Math.ceil((s.sideJob.end-Date.now())/1000)+'s':W.canCleanStation(o)?'Clean':'Prep +';label(o.x,o.z,text,'#fff9df',2.2);}if(o.type==='counter'){const count=o.stock.reduce((a,b)=>a+b,0);label(o.x,o.z,count?count+' servings':'Counter','#fff9df',2.1);}if(o.type==='bus_station')label(o.x,o.z,`Bus ${o.trash||0}🗑 ${o.dishes||0}🍽`,'#ffe8c8',2);if(s.washJob&&(o.type==='sink'||o.type==='dishwasher'))label(o.x,o.z,Math.ceil((s.washJob.end-Date.now())/1000)+'s wash','#dff5ff',2);if((o.type==='chair'||o.type==='table')&&o.tip){const p=project(o.x,o.z),r=Math.max(10,view.tx*.25),cy=p.y-view.tx*.6;ctx.beginPath();ctx.arc(p.x,cy+Math.sin(now/350)*2,r,0,Math.PI*2);ctx.fillStyle='#ffd646';ctx.fill();ctx.strokeStyle='#b78025';ctx.lineWidth=2;ctx.stroke();ctx.textAlign='center';ctx.fillStyle='#9c621c';ctx.font=`bold ${r*1.2}px Arial`;ctx.fillText('$',p.x,cy+r*.4+Math.sin(now/350)*2);hitboxes.push({id:o.id,x:p.x-r,y:cy-r,w:r*2,h:r*2});}}
for(const c of customers)if(c.phase==='counter'||c.phase==='ordered')label(c.x,c.z,(c.orderWait>=45?'⌛ ':'')+(R[c.recipe].icon||'🍕')+' '+R[c.recipe].name+(c.orderWait>=45?' · '+Math.max(0,60-Math.floor(c.orderWait))+'s':''),'#fff9df',2.2);
for(const c of customers)if(c.phase==='eat')label(c.x,c.z,'Yum!','#fff9df',1.95);
if(placement&&hover&&W.inside(s,hover)){const o={...placement.object,...hover};if(W.isSign(o)){if(o.x===0||o.z===0)wallSign(o,.65,false);}else sprite(W.spriteName(o),o.x,o.z,o.type==='plant'?1.05:o.variant==='lava'?.85:1.65,{alpha:.65,flip:(o.type==='decor'||o.type==='chair')&&o.rot===1});}
for(const f of floaters){if(f.kind==='reaction'){ctx.save();ctx.globalAlpha=Math.min(1,f.life/.25);label(f.guest.x,f.guest.z,f.text,'#f4eaff',2.15);ctx.restore();continue;}if(f.kind==='payment'){const p=project(f.guest.x,f.guest.z),font=Math.max(11,Math.min(14,view.tx*.32));ctx.save();ctx.globalAlpha=Math.min(1,f.life/.5,(2.8-f.life)/.2);ctx.font=`bold ${font}px Trebuchet MS,Arial`;const w=ctx.measureText(f.text).width+20,x=Math.max(w/2+6,Math.min(view.w-w/2-6,p.x)),y=Math.max(20,p.y-view.tx*3-(2.8-f.life)*5);rounded(x-w/2,y-16,w,28,10,'#e2fff0','#69ba95');ctx.fillStyle='#246347';ctx.textAlign='center';ctx.fillText(f.text,x,y+2);ctx.restore();continue;}const p=project(f.x,f.z);ctx.globalAlpha=Math.min(1,f.life);ctx.font=`bold ${Math.max(16,view.tx*.55)}px Trebuchet MS`;ctx.textAlign='center';ctx.lineWidth=3;ctx.strokeStyle='#fff3c8';ctx.strokeText(f.text,p.x,p.y-view.tx*2-(1.8-f.life)*30);ctx.fillStyle='#6b9235';ctx.fillText(f.text,p.x,p.y-view.tx*2-(1.8-f.life)*30);ctx.globalAlpha=1;}
}
function frame(now){if(W.finishSides(s,Date.now())){save();notify('Sides are ready! Open Orders to serve.');}if(s.washJob&&Date.now()>=s.washJob.end){s.washJob=null;s.floorDirt=Math.max(0,(s.floorDirt||0)-5);save();}if(panelMode==='orders'&&now-lastHud>500)ordersPanel();if(panelMode==='sides'&&now-lastHud>500)sidesPanel();const dt=Math.min((now-lastFrame)/1000||0,.05);lastFrame=now;if(!paused&&!build){if(!moveChef(dt)&&chefAction)finishChef();for(const c of [...customers])customerStep(c,dt);workStaff(dt);if(now>=nextArrival){spawnGuest(now);nextArrival=now+4000;}for(const f of floaters)f.life-=dt;floaters=floaters.filter(f=>f.life>0);}if(now-lastHud>500){hud();lastHud=now;if(panelMode==='oven'&&$('panel').open){const o=find(activeOven);if(o?.job&&$('bakeClock')){const ready=o.job.end<=Date.now();$('bakeClock').textContent=ready?'Ready!':Math.ceil((o.job.end-Date.now())/1000)+'s';$('collectBatch').disabled=!ready||!!chefAction;}}}draw(now);requestAnimationFrame(frame);}
function onTap(x,y){const tile=placementTileAt(x,y);if(build&&placement){placeAt(tile);return;}let hit=[...hitboxes].reverse().find(h=>x>=h.x&&x<=h.x+h.w&&y>=h.y&&y<=h.y+h.h);let o=hit?find(hit.id):W.at(s,tile.x,tile.z);if(!o)return;if(build){const k=shopKey(o);startPlacement(k||o.type,o.id);return;}if(o.type==='oven')ovenPanel(o);else if(o.type==='counter')counterPanel(o);else if(o.type==='chair'||o.type==='table')takeTip(o);else if(o.type==='cash')notify('Counter guests pay here before they take a seat.');else if(o.type==='bus_station')notify('Bussing station: '+((o.trash||0)+' trash, '+(o.dishes||0)+' dishes waiting.'));else if(o.type==='garbage_can')notify('Janitors empty trash from the bussing station into this can.');else if(o.type==='sink')notify('Hand-wash dishes here. Hire a Dishwasher or wash manually from the bus station flow.');else if(o.type==='dishwasher')notify('Commercial washer: 50% faster than the prep sink when staff is on duty.');else if(o.type==='fryer')notify(W.TYPES.fryer.description);else if(o.type==='soda')notify(W.TYPES.soda_dispenser.description);else if(W.isSign(o))notify((o.design==='neon'?'In Crust We Trust':o.design==='crust'?'crust&co':o.design==='pizza'?'Happy pizza plaque':'Solana')+' wall sign. Move it in Furniture mode.');else if(o.type==='decor')notify((o.variant==='lava'?'Lava glow lamp':'Hover pizza display')+'. Move, rotate or store it in Furniture mode.');else notify('A little green makes this corner feel like home.');}
canvas.addEventListener('pointerdown',ev=>{pointer={id:ev.pointerId,x:ev.clientX,y:ev.clientY,oldX:ev.clientX,oldY:ev.clientY,moved:false};canvas.setPointerCapture(ev.pointerId);});canvas.addEventListener('pointermove',ev=>{hover=placementTileAt(ev.clientX,ev.clientY);if(!pointer||pointer.id!==ev.pointerId)return;if(Math.hypot(ev.clientX-pointer.x,ev.clientY-pointer.y)>7)pointer.moved=true;if(pointer.moved&&!placement){const limitX=Math.max(innerWidth*.5,s.size*view.tx),limitY=Math.max(innerHeight*.4,s.size*view.ty);pan.x=Math.max(-limitX,Math.min(limitX,pan.x+ev.clientX-pointer.oldX));pan.y=Math.max(-limitY,Math.min(limitY,pan.y+ev.clientY-pointer.oldY));}pointer.oldX=ev.clientX;pointer.oldY=ev.clientY;});canvas.addEventListener('pointerup',ev=>{if(pointer&&!pointer.moved)onTap(ev.clientX,ev.clientY);pointer=null;});canvas.addEventListener('pointercancel',()=>pointer=null);
canvas.addEventListener('wheel',ev=>{ev.preventDefault();changeZoom(-Math.sign(ev.deltaY)*.12);},{passive:false});
$('saveGame').onclick=()=>notify(save()?'Game saved on this device.':'Could not save. Check browser storage.');setInterval(()=>{if(!paused)save();},15000);
$('zoomIn').onclick=()=>changeZoom(.25);$('zoomOut').onclick=()=>changeZoom(-.25);$('fitRoom').onclick=fitRoom;$('cook').onclick=()=>{if(build){notify('Press Done to leave furniture mode first.');return;}chooseOven();};$('decorate').onclick=shop;$('expand').onclick=expansion;$('help').onclick=help;$('tips').onclick=collectAllTips;$('closePanel').onclick=closePanel;$('panel').addEventListener('close',()=>panelMode='');$('finishBuild').onclick=finishBuild;$('cancelPlace').onclick=cancelPlacement;$('rotate').onclick=()=>{if(placement)placement.object.rot=1-placement.object.rot;};
document.addEventListener('keydown',ev=>{if(ev.key==='Escape'&&build){if(placement)cancelPlacement();else finishBuild();}if((ev.key==='r'||ev.key==='R')&&placement?.object.type==='chair')placement.object.rot=1-placement.object.rot;});
$('panelBody').addEventListener('click',ev=>{const b=ev.target.closest('button');if(!b)return;if(b.dataset.oven)ovenPanel(find(Number(b.dataset.oven)));if(b.dataset.recipe!==undefined)sendChef(find(activeOven),'bake',Number(b.dataset.recipe));if(b.id==='collectBatch')sendChef(find(activeOven),'collect');if(b.id==='cleanOven')sendChef(find(activeOven),'clean');if(b.dataset.buy)startPlacement(b.dataset.buy);if(b.id==='gotIt')closePanel();if(b.id==='buyExpansion'){const e=W.expansionInfo(s);if(!e.max&&s.coins>=e.price+12&&!chefAction){settleCustomers();if(W.expandRoom(s)){fitRoom();chef.x=W.entry(s).x;chef.z=W.entry(s).z;save();hud();closePanel();notify('Expansion '+W.expansionInfo(s).purchased+'/20 complete! Your restaurant is now '+s.size+' × '+s.size+'.');}}}});
window.addEventListener('resize',resize);window.addEventListener('pagehide',()=>{settleCustomers();save();});document.addEventListener('visibilitychange',()=>{paused=document.hidden;if(paused){settleCustomers();save();}else nextArrival=performance.now()+2000;});
Promise.all(SPRITES.map(name=>new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>{sprites[name]=img;resolve();};img.onerror=()=>reject(new Error(name));img.src='assets/'+name+'.png';}))).then(()=>{$('loading').hidden=true;resize();save();hud();requestAnimationFrame(frame);}).catch(()=>{$('loading').innerHTML='<strong>One moment…</strong><span>Some artwork could not load. Please refresh this page.</span>';});
